name: Daily Domain Warmup

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  warm:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This gives GitHub permission to update your website file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Nodemailer
        run: npm install nodemailer

      - name: Run Script & Update Webpage
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          DAILY_VOLUME: "2"
        run: node warmup.js

      - name: Commit and Push Webpage Changes
        run: |
          git config --global user.name "Warmup Bot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "Automated dashboard update [skip ci]" || exit 0
          git push
